GET http://localhost:3333/people
###
GET http://localhost:3333/jokes/6217723b04728287ae21348d
###

POST http://localhost:3333/people/
Content-Type: application/json

{
"text": "Test joke",
"author": "Jane Doe"
}

###
PATCH http://localhost:3333/people/1
Content-Type: application/json

{
"text": "This is changed again"
}

###
DELETE http://localhost:3333/people/6217723b04728287ae21348d

    